sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t multiproject/fe-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true multiproject/fe-test npm run test

after_success:
  - docker build -t serupadenganmu/multi-worker ./worker
  - docker build -t serupadenganmu/multi-server ./server
  - docker build -t serupadenganmu/multi-client ./server
  - docker build -t serupadenganmu/multi-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push serupadenganmu/multi-worker
  - docker push serupadenganmu/multi-server
  - docker push serupadenganmu/multi-client
  - docker push serupadenganmu/multi-nginx